// Minimal seed list of known-reliable camera feeds.
// Dynamic feeds are discovered at runtime by feedDiscovery.js.
// These serve as fallback if all dynamic sources fail.
export const CAMERA_FEEDS = [
    {
        id: 'worldcams-croatia-dubrovnik-stradun',
        name: 'Dubrovnik Stradun Live Feed',
        lat: 42.641359, lng: 18.108967, url: null, seed: true,
        videoUrl: 'https://cdn-004.whatsupcams.com/hls/hr_dubrovnik07.m3u8',
        resolvedVideoUrl: 'https://cdn-004.whatsupcams.com/hls/hr_dubrovnik07.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1555992336-03a23c7b20eb?auto=format&fit=crop&w=400&q=80',
        city: 'Dubrovnik', mediaType: 'video', provider: 'WorldCams', type: 'city',
    },
    {
        id: 'worldcams-germany-dusseldorf-airport',
        name: 'Dusseldorf Airport Live Feed',
        lat: 51.278459, lng: 6.768192, url: null, seed: true,
        videoUrl: 'https://stream-5gw.1000eyes.de/cupertino/dus5abb.stream/playlist.m3u8',
        resolvedVideoUrl: 'https://stream-5gw.1000eyes.de/cupertino/dus5abb.stream/playlist.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=400&q=80',
        city: 'Dusseldorf', mediaType: 'video', provider: 'WorldCams', type: 'city',
    },
    {
        id: 'worldcams-germany-hamburg-airport',
        name: 'Hamburg Airport Live Feed',
        lat: 53.633622, lng: 9.997413, url: null, seed: true,
        videoUrl: 'https://stream-5gw.1000eyes.de/cupertino/hamDDFB28.stream/playlist.m3u8',
        resolvedVideoUrl: 'https://stream-5gw.1000eyes.de/cupertino/hamDDFB28.stream/playlist.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1530521951415-3dbd69e12541?auto=format&fit=crop&w=400&q=80',
        city: 'Hamburg', mediaType: 'video', provider: 'WorldCams', type: 'city',
    },
    {
        id: 'worldcams-france-nancy-place-stanislas',
        name: 'Nancy Place Stanislas Live',
        lat: 48.6936, lng: 6.1832, url: null, seed: true,
        videoUrl: 'https://ds2-cache.quanteec.com/contents/encodings/live/aa29e970-6a9c-4f66-3437-3330-6d61-63-8898-aa10faedf4f4d/master.m3u8',
        resolvedVideoUrl: 'https://ds2-cache.quanteec.com/contents/encodings/live/aa29e970-6a9c-4f66-3437-3330-6d61-63-8898-aa10faedf4f4d/master.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=400&q=80',
        city: 'Nancy', mediaType: 'video', provider: 'WorldCams', type: 'landmark',
    },
    {
        id: 'worldcams-barbados-barbados-beaches',
        name: 'Barbados Carlisle Bay Beach',
        lat: 13.08833, lng: -59.614658, url: null, seed: true,
        videoUrl: 'https://stream.iwcpinc.com/IWCP_BEACH/_definst_/Carlisle_Bay_Radisson.stream/playlist.m3u8',
        resolvedVideoUrl: 'https://stream.iwcpinc.com/IWCP_BEACH/_definst_/Carlisle_Bay_Radisson.stream/playlist.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
        city: 'Barbados', mediaType: 'video', provider: 'WorldCams', type: 'landmark',
    },
    {
        id: 'worldcams-slovakia-besenova-aquapark-gino-paradise',
        name: 'Aquapark Gino Paradise',
        lat: 49.099976, lng: 19.445714, url: null, seed: true,
        videoUrl: 'https://stream.profi-net.sk/tmr/STREAM46.stream/playlist.m3u8',
        resolvedVideoUrl: 'https://stream.profi-net.sk/tmr/STREAM46.stream/playlist.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&w=400&q=80',
        city: 'Besenova', mediaType: 'video', provider: 'WorldCams', type: 'landmark',
    },
    {
        id: 'worldcams-serbia-belgrade-city-views',
        name: 'Belgrade Republic Square',
        lat: 44.815, lng: 20.46, url: null, seed: true,
        videoUrl: 'https://streamer.devnet.rs/hls/trgrepublike.m3u8',
        resolvedVideoUrl: 'https://streamer.devnet.rs/hls/trgrepublike.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1601058443950-12246d3a666e?auto=format&fit=crop&w=400&q=80',
        city: 'Belgrade', mediaType: 'video', provider: 'WorldCams', type: 'city',
    },
    {
        id: 'worldcams-canada-mississauga-celebration-square',
        name: 'Mississauga Celebration Square',
        lat: 43.58814, lng: -79.643007, url: null, seed: true,
        videoUrl: 'https://webvideo.mississauga.ca/StageWebcam/LiveStageWebcam.stream-audiodestin/playlist.m3u8',
        resolvedVideoUrl: 'https://webvideo.mississauga.ca/StageWebcam/LiveStageWebcam.stream-audiodestin/playlist.m3u8',
        fallbackUrl: 'https://images.unsplash.com/photo-1517089596392-db9a5e9478ec?auto=format&fit=crop&w=400&q=80',
        city: 'Mississauga', mediaType: 'video', provider: 'WorldCams', type: 'city',
    },
];

// Static airspace restricted zones (simplified GeoJSON)
export const RESTRICTED_AIRSPACE = [
    {
        id: 'dc-sfra',
        name: 'Washington DC SFRA',
        type: 'Restricted',
        center: [-77.0369, 38.9072],
        radius: 55000, // meters
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'dc-frz',
        name: 'Washington DC FRZ',
        type: 'Prohibited',
        center: [-77.0369, 38.9072],
        radius: 25000,
        color: 'rgba(255, 0, 0, 0.25)',
        borderColor: 'rgba(255, 0, 0, 0.8)',
    },
    {
        id: 'area51',
        name: 'Area 51 / Groom Lake',
        type: 'Restricted',
        center: [-115.8111, 37.235],
        radius: 40000,
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'camp-david',
        name: 'Camp David TFR',
        type: 'Prohibited',
        center: [-77.463, 39.648],
        radius: 18500,
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 0, 0, 0.6)',
    },
    {
        id: 'heathrow',
        name: 'London Heathrow CTR',
        type: 'Controlled',
        center: [-0.4543, 51.4700],
        radius: 15000,
        color: 'rgba(0, 180, 255, 0.1)',
        borderColor: 'rgba(0, 180, 255, 0.4)',
    },
];

// Publicly documented no-access / highly restricted places.
export const FORBIDDEN_ZONES = [
    {
        id: 'north-sentinel-island',
        name: 'North Sentinel Island',
        country: 'India',
        center: [92.233, 11.556],
        radius: 9000,
        type: 'Tribal Protection Zone',
        status: 'NO ENTRY',
        severity: 'EXTREME',
        reason: 'Protected uncontacted tribe area. Entry is prohibited.',
        access: 'Prohibited by law',
        source: 'Government-protected tribal reserve',
        reference: 'https://en.wikipedia.org/wiki/North_Sentinel_Island',
        color: 'rgba(255, 0, 0, 0.22)',
        borderColor: 'rgba(255, 50, 50, 0.82)',
    },
    {
        id: 'chernobyl-exclusion-zone',
        name: 'Chernobyl Exclusion Zone',
        country: 'Ukraine',
        center: [30.221, 51.276],
        radius: 30000,
        type: 'Radiation Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Long-term radiation contamination after nuclear disaster.',
        access: 'Permit only / controlled tours',
        source: 'State exclusion regime',
        reference: 'https://en.wikipedia.org/wiki/Chernobyl_Exclusion_Zone',
        color: 'rgba(255, 80, 0, 0.2)',
        borderColor: 'rgba(255, 130, 0, 0.8)',
    },
    {
        id: 'fukushima-exclusion-zone',
        name: 'Fukushima Restricted Zone',
        country: 'Japan',
        center: [141.032, 37.421],
        radius: 20000,
        type: 'Radiation Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Nuclear contamination control area after 2011 disaster.',
        access: 'Controlled re-entry zones only',
        source: 'Government evacuation/restriction orders',
        reference: 'https://en.wikipedia.org/wiki/Fukushima_Daiichi_nuclear_disaster',
        color: 'rgba(255, 80, 0, 0.18)',
        borderColor: 'rgba(255, 140, 0, 0.76)',
    },
    {
        id: 'korean-dmz',
        name: 'Korean Demilitarized Zone',
        country: 'Korea Peninsula',
        center: [126.676, 37.956],
        radius: 42000,
        type: 'Demilitarized Buffer',
        status: 'NO CIVILIAN ENTRY',
        severity: 'EXTREME',
        reason: 'Heavily fortified border buffer between North and South Korea.',
        access: 'Military controlled',
        source: 'Armistice border regime',
        reference: 'https://en.wikipedia.org/wiki/Korean_Demilitarized_Zone',
        color: 'rgba(255, 0, 0, 0.18)',
        borderColor: 'rgba(255, 40, 40, 0.8)',
    },
    {
        id: 'area-51',
        name: 'Area 51',
        country: 'United States',
        center: [-115.8111, 37.235],
        radius: 26000,
        type: 'Military Test Range',
        status: 'NO ENTRY',
        severity: 'EXTREME',
        reason: 'Classified military facility with strict perimeter enforcement.',
        access: 'Prohibited',
        source: 'US military restricted area',
        reference: 'https://en.wikipedia.org/wiki/Area_51',
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 30, 30, 0.85)',
    },
    {
        id: 'diego-garcia-base',
        name: 'Diego Garcia Military Facility',
        country: 'British Indian Ocean Territory',
        center: [72.411, -7.313],
        radius: 16000,
        type: 'Military Facility',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Strategic military island installation.',
        access: 'Authorized personnel only',
        source: 'Military installation restrictions',
        reference: 'https://en.wikipedia.org/wiki/Diego_Garcia',
        color: 'rgba(255, 35, 35, 0.18)',
        borderColor: 'rgba(255, 90, 90, 0.78)',
    },
    {
        id: 'snake-island-brazil',
        name: 'Ilha da Queimada Grande (Snake Island)',
        country: 'Brazil',
        center: [-46.675, -24.488],
        radius: 6500,
        type: 'Ecological Prohibition',
        status: 'NO PUBLIC ENTRY',
        severity: 'HIGH',
        reason: 'Protected island with extreme venomous snake density.',
        access: 'Navy/research only',
        source: 'Brazilian environmental / naval control',
        reference: 'https://en.wikipedia.org/wiki/Ilha_da_Queimada_Grande',
        color: 'rgba(255, 70, 0, 0.16)',
        borderColor: 'rgba(255, 120, 0, 0.78)',
    },
    {
        id: 'surtsey-island',
        name: 'Surtsey Island',
        country: 'Iceland',
        center: [-20.605, 63.303],
        radius: 7000,
        type: 'Scientific Reserve',
        status: 'NO PUBLIC ENTRY',
        severity: 'MEDIUM',
        reason: 'Protected natural laboratory for ecological succession research.',
        access: 'Scientists with permission only',
        source: 'UNESCO/State protection',
        reference: 'https://en.wikipedia.org/wiki/Surtsey',
        color: 'rgba(255, 160, 0, 0.14)',
        borderColor: 'rgba(255, 190, 0, 0.72)',
    },
    {
        id: 'niihau-island',
        name: 'Niihau Island',
        country: 'United States',
        center: [-160.154, 21.899],
        radius: 15000,
        type: 'Private Restricted Island',
        status: 'NO PUBLIC ENTRY',
        severity: 'MEDIUM',
        reason: 'Privately owned island with controlled access.',
        access: 'Owner-approved only',
        source: 'Private ownership restrictions',
        reference: 'https://en.wikipedia.org/wiki/Niihau',
        color: 'rgba(255, 180, 0, 0.14)',
        borderColor: 'rgba(255, 210, 0, 0.72)',
    },
    {
        id: 'lascaux-cave',
        name: 'Lascaux Cave',
        country: 'France',
        center: [1.167, 45.053],
        radius: 2200,
        type: 'Heritage Preservation',
        status: 'CLOSED',
        severity: 'MEDIUM',
        reason: 'Original cave closed to preserve prehistoric paintings.',
        access: 'No public entry',
        source: 'Cultural heritage preservation',
        reference: 'https://en.wikipedia.org/wiki/Lascaux',
        color: 'rgba(255, 140, 0, 0.16)',
        borderColor: 'rgba(255, 170, 0, 0.74)',
    },
    {
        id: 'mezhgorye-closed-city',
        name: 'Mezhgorye Closed City',
        country: 'Russia',
        center: [57.817, 54.049],
        radius: 12000,
        type: 'Closed Administrative Area',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Closed city with restricted external access.',
        access: 'Government authorization only',
        source: 'Closed city regime',
        reference: 'https://en.wikipedia.org/wiki/Mezhgorye,_Republic_of_Bashkortostan',
        color: 'rgba(255, 60, 60, 0.15)',
        borderColor: 'rgba(255, 100, 100, 0.75)',
    },
    {
        id: 'zone-rouge-france',
        name: 'Zone Rouge',
        country: 'France',
        center: [5.43, 49.22],
        radius: 17000,
        type: 'War Remnants Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'WWI unexploded ordnance and contamination zone.',
        access: 'Restricted / controlled activity',
        source: 'French state safety restrictions',
        reference: 'https://en.wikipedia.org/wiki/Zone_Rouge',
        color: 'rgba(255, 90, 0, 0.14)',
        borderColor: 'rgba(255, 130, 0, 0.72)',
    },
    {
        id: 'bikini-atoll',
        name: 'Bikini Atoll Nuclear Test Site',
        country: 'Marshall Islands',
        center: [165.386, 11.606],
        radius: 24000,
        type: 'Nuclear Legacy Zone',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Historic nuclear test area with long-term contamination concerns.',
        access: 'Controlled access',
        source: 'Nuclear test legacy restrictions',
        reference: 'https://en.wikipedia.org/wiki/Bikini_Atoll',
        color: 'rgba(255, 90, 0, 0.16)',
        borderColor: 'rgba(255, 140, 0, 0.75)',
    },
    {
        id: 'punggye-ri-test-site',
        name: 'Punggye-ri Test Site Zone',
        country: 'North Korea',
        center: [129.083, 41.3],
        radius: 10000,
        type: 'Nuclear Test Security Zone',
        status: 'NO PUBLIC ENTRY',
        severity: 'EXTREME',
        reason: 'Restricted military zone associated with underground nuclear testing.',
        access: 'Prohibited',
        source: 'State military security controls',
        reference: 'https://en.wikipedia.org/wiki/Punggye-ri_Nuclear_Test_Site',
        color: 'rgba(255, 30, 30, 0.2)',
        borderColor: 'rgba(255, 80, 80, 0.85)',
    },
    {
        id: 'mount-weather',
        name: 'Mount Weather Emergency Operations Center',
        country: 'United States',
        center: [-77.886, 39.062],
        radius: 7000,
        type: 'Government Security Site',
        status: 'NO PUBLIC ENTRY',
        severity: 'HIGH',
        reason: 'High-security continuity-of-government facility.',
        access: 'Authorized personnel only',
        source: 'Federal security restrictions',
        reference: 'https://en.wikipedia.org/wiki/Mount_Weather_Emergency_Operations_Center',
        color: 'rgba(255, 40, 40, 0.16)',
        borderColor: 'rgba(255, 80, 80, 0.75)',
    },
    {
        id: 'heard-island-reserve',
        name: 'Heard Island & McDonald Islands Reserve',
        country: 'Australia',
        center: [73.51, -53.08],
        radius: 22000,
        type: 'Environmental Protection Zone',
        status: 'PERMIT REQUIRED',
        severity: 'MEDIUM',
        reason: 'Remote subantarctic reserve with strict permit-only entry controls.',
        access: 'Permit required',
        source: 'Australian Antarctic Division permit regime',
        reference: 'https://www.antarctica.gov.au/about-antarctica/australian-antarctic-territory/heard-island/',
        color: 'rgba(255, 140, 0, 0.12)',
        borderColor: 'rgba(255, 175, 0, 0.68)',
    },
];
